### ISSUE TITLE
ロゴ決め

### ISSUE THREAD

**Issue by k2wanko** [firebasejp/task#1]
Firebase Japan User Groupのロゴをどうするか

**Comment by k2wanko** [comment]
予算があればCloud Worksとかに頼みたい気持ちはある

**Comment by tomo667a** [comment]
誰かが言っていた ファイヤージャグリング をモチーフにする案がいいと思いました

**Comment by Yatima-Kagurazaka** [comment]
FireJUG ふぁいあーじゃぐ　でジャグリングにするか
FireJpUG ふぁいあーじぇいぱぐ　でまたパグにするか（）

予算なければわしがつくる
予算あってもラフは押し付けたい or ラフとりあえず作ってもらって良い方選ぶ，でもいいけど

**Comment by Yatima-Kagurazaka** [comment]
いまのきもち
ジャグリングなら，金属製のアレを人の字みたいに並べて，持ち手は上で先端に炎
パグなら，パグの目に炎（GCPUGのパグ連れてきたい）
どっちも炎は公式ロゴ？でも安っぽく見える恐れも（クソコラてきな）

**Comment by Yatima-Kagurazaka** [comment]
まぁ
GCPUGのパグ使っちゃえば
関連性もわかりやすいし，作るのも楽，ってのはあるか
逆に，雰囲気として従属意識が強くなってしまう恐れもあるのはある

**Comment by k2wanko** [comment]
略を意識的にfirejpugにしてるのはfirej**pug**でpugを中に入れたいからなんですよね。
ロゴもパグのがいいかなと思っていますが
あんまりGCPUGに引きづられなくてもいいかなとも思ってます。

ただ GCPに則って六角に収まるいい感じにはしたいですね。

**Comment by Yatima-Kagurazaka** [comment]
いめーじしているざつこら
![firejpug.png](https://static1.squarespace.com/static/598096b06b8f5b693bdfbb87/5a10d51e41920282355b7ee8/5a10d52a08522939d94d3f3b/1511052587729/firejpug.png?format=1500w)

**Comment by Yatima-Kagurazaka** [comment]
とりあえず，たぶん公式ロゴの使用はだめっぽいな
AWSとかAzureでも使ってないし
そこはいずれにせよ差し替え

**Comment by k2wanko** [comment]
これで決まりました。

![firebase-japan-user-group_03-2a](https://user-images.githubusercontent.com/4466222/33370601-67326d86-d53b-11e7-9854-abc85f4269fb.png)
