### ISSUE TITLE
staff channelの分け方

### ISSUE THREAD

**Issue by k2wanko** [firebasejp/task#19]
色んなイベントが重なってきたので、さすがにそろそろ分けるかということになったので
分けます。

分け方に案がある人はここのコメントください

**Comment by Yatima-Kagurazaka** [comment]
イベントごとのチャンネル + シャツチャンネル，ステッカーチャンネル

**Comment by w2-yamaguchi** [comment]
先日のミーティングで話した担当ごとに分ける案

* オーガナイザー
* シャツ/ステッカー
* アプリ企画
* ハンズオン企画

**Comment by k2wanko** [comment]
#organizer (private)
#novelty (private)
#イベントごと (private)
↑この辺は個人情報とか金銭周りが絡む可能性があるから権限を絞る

#dev-app
#dev-web
この辺はオープンにしたい

**Comment by w2-yamaguchi** [comment]
@k2wanko 案で違和感なし！

**Comment by k2wanko** [comment]
分けた
