### ISSUE TITLE
Firebase Japan User Group / meetup / 1 (12/16)

### ISSUE THREAD

**Issue by k2wanko** [firebasejp/task#2]
[Laurence](https://twitter.com/lmoroney)さんが12月に日本に来るとのことなのでそこらへんでEventを行う予定。

12/16 15:00~ about 3h

Place: 六本木ヒルズ (詳細はあとで)
Logistics: VR
After Party: Google Support

# Schedule

|時間   | 内容 | スピーカー|
|---|---|---|
|14:30 ~ |開場/受付   |
|15:00 ~ 15:10| Firebase Japan User Group について  | @k2wanko |
|15:10 ~ 17:10| Firebase Overview, including everything that we've announced in the last few weeks, and then a deep dive into Cloud Functions for Firebase  | @lmoroney |
|17:10 ~ 17:20| 休憩  |  |
|17:20 ~ 17:50| db設計について（仮）  | @Yatima-Kagurazaka |
|17:50 ~ 18:20| 新機能周りか、serverlessconfでやったDBとのInterfaceの話  | @d-date |
|18:20 ~ | After party  |  |

# Session

## Firebase Japan User Group について @k2wanko 10min

コミュニティの紹介をします。

## 新機能周りか、serverlessconfでやったDBとのInterfaceの話 @d-date 30m

# Tasks
- [x] 会場用意
- [x] Speaker集め
- [x] アンケートフォーム作成
- [x] 募集ページ作成

**Comment by k2wanko** [comment]
scheduleは12/16 15:00 ~ 18:00 で確定
場所もGoogle Officeで確定

**Comment by Yatima-Kagurazaka** [comment]
喋るぞい
db設計について（仮）

**Comment by k2wanko** [comment]
@Yatima-Kagurazaka Firestore?

**Comment by d-date** [comment]
iOS視点でなんか話しますー

新機能周りか、serverlessconfでやったDBとのInterfaceの話かなー

**Comment by k2wanko** [comment]
アンケートフォーム
https://goo.gl/forms/W5kkPfR2gUcnnHou1

**Comment by k2wanko** [comment]
Blog書いたら閉じます。
