### ISSUE TITLE
スピーカー決め

### ISSUE THREAD

**Issue by k2wanko** [firebasejp/task#24]
セッションは 30min * 7 なので 7枠埋める必要がある
(8から7になった)

status: https://docs.google.com/spreadsheets/d/18AcX8WZ5P4Fk0dvNc9EQ5NBA4uNFlL9nvp_kLPpakL0/edit?usp=drive_web&ouid=100682397188809163845

## スピーカー候補

- [x] Yatimaさん Cloud Functions系でなにか、もしくはFirestore👌  
- [x] d_dateさん iOSやFirebase全般でなにかあれば 👌 
- [x] 1amageekさん Client Sideの実装について話してくれることがあれば👌 
- [x] きりんさん mercariの事例とか話してくれることがあれば 👌 
- [x] monoさん FirestoreとかiOSの実装周りで話してくれそうなことがあれば 🙅 
- [x] gerimitoさん Unityとかゲーム関連で話してくれそうなら 👌 
- [x] ブルーノさん RealtimeDBかCAの事例で話してくれそうなら 👌 
- [x] daquroさん 広告周りで話してくれそうなら 🙅

**Comment by k2wanko** [comment]
予備で k2wankoが待機

**Comment by k2wanko** [comment]
話すとしたらFirebase Authとかセキュリティルールで

**Comment by ipros-watanabe** [comment]
@k2wanko 
話す人が足りなかったら、Hosting + Functions周りで初心者向けの内容なら話せます

**Comment by kappa0923** [comment]
@k2wanko 
アカウント間違えたので改めて……
話す人が足りなかったら、Hosting + Functions周りで初心者向けの内容なら話せます

**Comment by k2wanko** [comment]
@kappa0923 お、ありがとうございます！

**Comment by Yatima-Kagurazaka** [comment]
monoさんdaquroさんNG
ブルーノさんOK

**Comment by Yatima-Kagurazaka** [comment]
shihochanさんOK

**Comment by k2wanko** [comment]
7人なので〆で
