### ISSUE TITLE
技術書典5

### ISSUE THREAD

**Issue by k2wanko** [firebasejp/task#35]
Firebaseについての本を書く予定 (当選したら)

書きたい人はコメントください。

# ToDo
- [x] 申し込み
- [x] 書く人決め
- [x] 書く
- [x] 印刷発注
- [x] 売る

**Comment by k2wanko** [comment]
FirebaseのIntroductionについて書きます。
余力があればAuthについても書きます。

**Comment by k2wanko** [comment]
欲しいネタ(もちろんそれ以外でもOK)

- Cloud Firestore
- Cloud Functions
- Remote Config
- 開発についての知見
- 実際作ったアプリ
- などなど

**Comment by k2wanko** [comment]
https://github.com/orgs/firebasejp/projects/5

**Comment by k2wanko** [comment]
当選したのでやっていくぞ！

**Comment by k2wanko** [comment]
書くもの案  #37

**Comment by w2-yamaguchi** [comment]
詳しさレベルは皆様に劣るけど、お手伝いしたい、かきたい

**Comment by k2wanko** [comment]
@w2-yamaguchi 何か書きたいことありますか？
