### ISSUE TITLE
何を書くか決める

### ISSUE THREAD

**Issue by k2wanko** [firebasejp/task#37]
# ターゲット案
- Web技術者のための
- 個人開発もしくはスタートアップのための

初心者に優しいものを想定する。
あまり多くの機能を説明せずに一直線でアプリケーションが構築できるようなガイドにする。
（「Emailだけではなく、GitHubやTwitter認証の他にも匿名認証もできます」といったことを触れても詳細は解説しない）

# タイトル案
- Web技術者のためのFirebase 入門 (Web, JavaScript)
- Firebase for React Native (React Native,JavaScript, Android, iOS)

# コンテンツ案

1. Firebaseとは
  - 簡単な歴史
  - 誰のためのものなのか
  - 何があるのか
  - 開発環境の構築
2. Authentication
  - Firebase Authenticationとは
  - Email認証の実装
3. Firestore
  - Firestore とは
  - 設計
  - Quick start Firestore
  - Security Rule
  - Tips
4. Firebaseを知るには
  - ドキュメントの読み方の説明
  - Firebase Japan User Groupの紹介

**Comment by k2wanko** [comment]
Realtime DatabaseとFirestore両方説明しようかと思ったけど
Firestoreだけにしたほうが混乱なさそうかな

**Comment by w2-yamaguchi** [comment]
firestoreの後にhostingを入れて
一冊で最終的に動くものが公開されると面白そう

**Comment by flatfisher** [comment]
Hosting やるんであれば、カスタムドメインの設定やfirebase.jsonの書き方も言及するとプロダクション（個人開発もしくはスタートアップのための）で使いたい人に需要ありそう

**Comment by kappa0923** [comment]
であればfunctionsとの接続も欲しいですね
トリガーも一通り網羅する感じで
