### ISSUE TITLE
Blog作成

### ISSUE THREAD

**Issue by k2wanko** [firebasejp/task#9]
# 背景

勉強会のレポートとか告知をできるブログが欲しい

# 要件

- メンバーがブログを作成編集できるようにしたい

# プラン

ブログをどうやって作るか？
- static file を生成してくれる blog cmsを使う https://hexo.io/
- hatenablogを使う？

ドメインはどうするか？
- https://blog.firebase.asia
- https://firebase.asia/blog

**Comment by Yatima-Kagurazaka** [comment]
https://www.webprofessional.jp/keystonejs-best-node-js-alternative-wordpress/
これは管理画面自動生成とか良いっぽいけど，hexoと比べるとstatic吐かないっぽいという意味では，退化感は否めない

そして個人的にははてなブログ推し（マーケティング的に）

**Comment by k2wanko** [comment]
ゆくゆくはFirebaseをバックエンドにブログシステムも作りたいので移行は簡単にしておきたい気持ちはあります
URLを変えなくていい感じにはしておきたいかなー
はてなブログでもエクスポートとURLをそのままに移行できそうならいいかなー

**Comment by k2wanko** [comment]
システムを作る暇がないのでやる気に満ちたときにやりたい気持ち

一旦既存のブログシステムを使いたい

案
- medium
- はてなブログ
- Ghost

**Comment by k2wanko** [comment]
https://medium.com/firebase-japan-user-group
